### ISSUE TITLE
Crashes on 1.19.2

### ISSUE THREAD

**Issue by iinterp** [tildejustin/planifolia#3]
Tested alone and with sodium, (seemingly) same crash log.

Tested with:
`planifolia-1.0.1+1.19-1.20.6.jar`

`Fabric Loader 0.15.11`
`Java 20.0.1`
`Minecraft 1.19.2`

[Crash log (only planifolia)](https://mclo.gs/5u4WSuR)

Also tried with the planifolia version on this github repo, also crashed.

Tested with:
`planifolia-1.0.0+1.19+.jar`
`sodium-fabric-mc1.19.2-0.4.4+build.18.jar`

`Fabric Loader 0.15.11`
`Java 20.0.1`
`Minecraft 1.19.2`

[Crash log](https://mclo.gs/OOhniXJ)

**Comment by tildejustin** [comment]
oh yeah i remember getting confused on the intermediary name for this one, it's a simple fix. also i forgot to release 1.0.1 here, thanks for the reminder 😅
